server:
  port: 8089
spring:
  application:
    name: zuulGateway  # 项目名称
eureka:
  client:
    fetch-registry: true # 示应用启动后不需要从服务治理服务器中同步已注册的服务注册列表数据到本地。
    register-with-eureka: true # 是否要注册到其他 eureka 服务器上
    service-url: # 服务发现项目地址
      defaultZone: http://localhost:8090/eureka/
zuul: # 手动指定服务的转发地址
  routes:
    api-a:
      path: /api/**  # 所有符合 path 的规则都被转发到 url 这个地址
      url: http://localhost:8095
    api-b:
      path: /user/**
      serviceId: userService # 通过serviceId来指定服务名称
    sensitive-headers: Cookie,Set-Cookie,Authorization # 请求头敏感信息


# 注：网关有默认路由配置规则，Zuul配合Eureka后将会成一套默认的配置规则。
# 当我们使用服务名称作为请求的前缀路径时，实际上就会匹配上类似下面的默认路由配置
# zuul:
#  routes:
#    server-consumer:
#      path: /服务名称/**
#      serviceId: 服务名称
#
