spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /client

attachment:
  location: /attachment/
  domain: http://127.0.0.1:8081${server.servlet.context-path}
  allow-format: png,jpg,jpeg,gif   # 允许上传的格式
  max-size: 4  # 大小限制4MB
