server:
  port: 8088

spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password: password
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sakila?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      data-source-properties:
        useSSL: false
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #在控制台打印SQL语句
    cache-enabled: true # 开启二级缓存
  type-aliases-package: com.example.distributedLock.bean # type-aliases扫描路径
  mapper-locations: classpath:mapper/*.xml  # mapper.xml 扫描路径