server:
  port: 8080

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://127.0.0.1:3306/oauth?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/oauth?allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
#    schema: classpath:db/schema.sql # 数据库初始化配置
#    data: classpath:db/data.sql
#    hikari:
#      data-source-properties:
#        useSSL: false
#        serverTimezone: GMT+8
#        useUnicode: true
#        characterEncoding: utf8
  datasource: # h2数数据库配置
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    schema: classpath:db/schema.sql # 数据库初始化配置
    data: classpath:db/data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #在控制台打印SQL语句
    cache-enabled: true # 开启二级缓存
  type-aliases-package: com.example.record.entity # type-aliases扫描路径
  mapper-locations: classpath:mapper/*.xml  # mapper.xml 扫描路径

logging:
  level:
    org.springframework.security: debug