spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: 0
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5

server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /record

attachment:
  location: /attachment/
  domain: http://127.0.0.1:8081${server.servlet.context-path}
  allow-format: png,jpg,jpeg,gif   # 允许上传的格式
  max-size: 4  # 大小限制4MB
