server:
  port: 8088

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 11love11
    hikari:
      data-source-properties:
        useSSL: false
        serverTimezone: GMT+8
        useUnicode: true
        characterEncoding: utf8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #在控制台打印SQL语句
    cache-enabled: true # 开启二级缓存
  type-aliases-package: com.example.record.entity # type-aliases扫描路径
  mapper-locations: classpath:mapper/*.xml  # mapper.xml 扫描路径

wxpay:
  appId: xxxxx
  mchId: xxxxx
  mchKey: xxxxx
  appSecret: xxxx
  keyPath: classpath:test/xxxx.p12
  notifyUrl: http://localhost:8088/callback
  refundNotifyUrl: http://localhost:8088/refund

alipay:
  appId: xxxx
  privateKey: xxxxx
  publicKey: xxxx
  serverUrl: http://localhost:8980
  domain: openapi.alipay.com
  returnUrl: http://localhost:8960/sign
  notifyUrl: http://localhost:8980/notify_url
  refundNotifyUrl: xxxx